### ISSUE TITLE
Symlink Issue: "Access is Denied" and "SpectatorView (Missing Prefab)"

### ISSUE THREAD

**Issue by BastiaanGrisel** [microsoft/MixedReality-SpectatorView#135]
Hi all, spectator mode looks like a great feature! Unfortunately I haven't yet been able to get something to work. My goal is to get one of the samples up and running with my Hololens 1 and Android phone, mainly to create high-quality videos for marketing/demoing purposes.

I followed the documentation in the [Samples ReadMe](https://github.com/microsoft/MixedReality-SpectatorView/tree/master/samples) and in [this PR](https://github.com/microsoft/MixedReality-SpectatorView/pull/130/files?short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8).

### Steps
1. Clone the `release/1.0.0-beta` branch of this repo in `C:\sv`
2. Right click "Run as Administrator" on `ResetSamples.bat`. This launches a powershell and clones some repositories. This takes about 2 minutes. The powershell closes again when it is done. 
3. If I open the project in Unity 2018.3.14f1 I get "Access is Denied" errors in the console (shown below under Images)
4. If I open the Unity editor by finding the editor executable (.exe) file and right clicking "Run as Administrator" and then open the project, I do not get these errors. But then if I close and reopen Unity without right clicking "Run as Administrator", the errors are still gone (so I don't know what is going on there).
5. With the "Access is Denied" errors gone, open `Demo/Scenes/Finished_Scene` and click "Import TMP Essentials" when prompted.
6. Observe the following:
a. 	The `SpectatorView` prefab is missing in the scene hierarchy 
b. 	There are errors in the console
c. 	The project hierarchy (it seems that the symlinks are not correctly followed?)

### Images
3:
![AccessIsDenied](https://user-images.githubusercontent.com/1348869/61723753-efa2ae00-ad6c-11e9-904d-ce6eb8d7e82e.PNG)

6a:
![SceneHierarchy](https://user-images.githubusercontent.com/1348869/61723751-efa2ae00-ad6c-11e9-8bb5-2ca78d7ea55c.PNG)

6b:
![ErrorsInConsole](https://user-images.githubusercontent.com/1348869/61723752-efa2ae00-ad6c-11e9-9923-903a2ff66879.PNG)

6c:
![ProjectHierarchy](https://user-images.githubusercontent.com/1348869/61723754-f03b4480-ad6c-11e9-8f74-41450e7fed66.PNG)

**Comment by matthejo** [comment]
Thanks for reporting this! If you open a command prompt and run "git status", do you see pending changes in the repository for any of the symlinks? These pending changes might look like this.

![image](https://user-images.githubusercontent.com/10050922/61731795-193de400-ad31-11e9-99e3-d37432783287.png)

If you are seeing these pending "typechange" changes, then this is an issue that is fixed in the master branch's SetupRepository script, but not in the release/1.0.0-beta. A quick fix while remaining on release/1.0.0-beta would be to run "git checkout -- ." from the root of the repository (this assumes you have no other changes). Git will then restore the symlinks automatically.

If that's not the issue, please let us know and we'll continue to try to help troubleshoot!

**Comment by BastiaanGrisel** [comment]
Thanks for the quick response! There was indeed a typechange which was removed when executing `git checkout -- .` However, the two errors (6b) are still present and the prefab (6a) is still missing.

![TypeChange](https://user-images.githubusercontent.com/1348869/61736509-8891f300-ad86-11e9-8aaf-0247d55eef30.PNG)

If I look at the symlink `C:\sv\samples\Build2019Demo.Unity\Assets\MixedReality-SpectatorView`, it does point to `C:\sv\src\SpectatorView.Unity` which does contain the `C:\sv\src\SpectatorView.Unity\Assets\SpectatorView\Prefabs\SpectatorView.prefab` that is missing in the scene hierarchy.

**Comment by matthejo** [comment]
I'm not sure why the prefab would still appear to be missing, but I think I would start with the errors first, and once those are resolved we can move on to the prefab if it's still not loading.

Regarding the errors in 6b: From 6c, it looks like the 4 symbolic link directories under MixedRealityToolkit-Unity are broken. They should appear as directories, like so.

![image](https://user-images.githubusercontent.com/10050922/61741559-08e43400-ad46-11e9-967c-845544cad0c2.png)

I think one of two things could be wrong:
1. The submodule for the MixedRealityToolkit-Unity was not initialized or cloned correctly, and so the target directories for the symlink don't exist. Can you check under :/external/MixedRealityToolkit-Unity to see if the directory is populated? If the directory is empty, try running 'git submodule update --init --force' from the root of the repository. You should see this output, and you should have the submodule populated. If there are errors, that would be interesting to know.

![image](https://user-images.githubusercontent.com/10050922/61741897-ba836500-ad46-11e9-886f-b509235083d6.png)

If this was the issue, running ResetSamples.bat should now fix the symbolic links.

2. If the MixedRealityToolkit-Unity submodule is cloned, then for some reason the directory symlinks aren't being restored correctly by the ResetSamples script.  If you look at :/samples/Build2019Demo.Unity/Assets/MixedRealityToolkit-Unity in Windows Explorer, do you see those 4 symbolic links showing up as directories?

![image](https://user-images.githubusercontent.com/10050922/61741764-72644280-ad46-11e9-9d17-91fd0638aad6.png)

If they are not showing up as folders, and instead look like iconless files, try deleting all 4 manually from Windows Explorer. Then run 'git checkout -- .' from a command prompt to restore them.



Based on what is wrong in your case, we can look at how to make these scripts more robust.

**Comment by BastiaanGrisel** [comment]
Thanks! The submodule directories are populated. When removing the contents of the MixedRealityToolkit-Unity folder, running `git checkout -- .` restores it back to the same state:

![Symlinks](https://user-images.githubusercontent.com/1348869/61779155-76549b00-ae00-11e9-9142-a8bb0d8d2083.PNG)

I reinstalled git (now version 2.22.0) since I figured I might have an old version and stumbled upon this option in the git installer:

![EnableSymbolicLinksGit](https://user-images.githubusercontent.com/1348869/61779174-80769980-ae00-11e9-937f-4dd620fe7f9e.PNG)

I checked the **Enable symbolic links** checkbox since it is unchecked by default, re-cloned the repository, switched branches to `release/1.0.0-beta` and ran `ResetSamples.bat`. The folder now looks like this, the Unity errors are gone and the prefab is found:

![SymlinksWorking](https://user-images.githubusercontent.com/1348869/61779187-84a2b700-ae00-11e9-9d9f-8efd1a757335.PNG)

Now onto the [next steps](https://github.com/microsoft/MixedReality-SpectatorView/blob/7f9a0af04fdfd53bb8829d4ec23c20525f658c80/samples/Build2019Demo.Unity/README.md) of running the BUILD2019 demo on my Hololens 1 and Android phone. Thanks a lot for the help and I will open a new issue if I stumble upon further problems.

**Comment by chrisfromwork** [comment]
Thank you, Bastiaan. We greatly appreciate this feedback and will work to improve our documentation/setup process.

**Comment by chrisfromwork** [comment]
I'm going to go ahead and close this for now. We have updated our documentation to describe how to setup submodules. In the master branch, SetupRepository.bat and FixSymbolicLinkedDirectories.bat should fix this issue. I tested things locally and we determined that skipping the enable symbolic linked directories git install option didn't seem to impact whether these bat scripts succeeded.

Please reopen this issue if you have additional suggestions or experience something similar again in the future. And most of all, thanks again for this feedback!
