### ISSUE TITLE
Getting error when  using the HolographiCamera.Unity project to my HoloLens 2 device

### ISSUE THREAD

**Issue by rdikshit** [microsoft/MixedReality-SpectatorView#376]
error 1: Deployed the HolographiCamera.Unity project to my HoloLens 2 device.getting the error below

![error](https://user-images.githubusercontent.com/6644233/81938599-bfa5ef00-95ba-11ea-99c9-1bf350d89908.jpg)

error 2 : Step 11 from [here](https://microsoft.github.io/MixedReality-SpectatorView/doc/SpectatorView.Setup.VideoCamera.html) I get errors 
![error2](https://user-images.githubusercontent.com/6644233/81938898-35aa5600-95bb-11ea-91e1-2f07b5a4e868.jpg)

**Comment by chrisfromwork** [comment]
There is a review out against master that should fix these vcrt forwarders errors that you are seeing in the editor when running the SpectatorView.ExtrinsicsCalibration scene. I do not believe these are related to the errors you are seeing for the HolographicCamera application running on the HoloLens 2 device.

When testing out things locally I do not see these errors for the Holographic Camera app. A missing Network connection manager prefab suggests that the Default Connection Manager Prefab specified in the SpectatorView.HolographicCamera prefab for the HolographicCamera scene is not populated correctly. It appears that in master, opening the src\HolographicCamera.Unity project and the HolographicCamera scene, that the prefab is still valid:

![Screenshot (53)](https://user-images.githubusercontent.com/10225640/81966838-ef5ef200-95ce-11ea-8bb2-189cd30eed9b.png)

HolographicCameraBroadcaster is a child class of NetworkManager, so the specific error you are seeing occurs here:
https://github.com/microsoft/MixedReality-SpectatorView/blob/c60d2a049a75892137f2b8eb54ccdede1de43268/src/SpectatorView.Unity/Assets/SpectatorView/Scripts/StateSynchronization/NetworkManager.cs#L181

My best guess is that one of two things may have happened:
1. The SpectatorView.HolographicCamera broadcaster in your local project has become corrupted. This can be fixedby specifying the TCPConnectionManager prefab as your Default Connection Manager Prefab.
2. The HolographicCamera scene was not correctly specified as the included scene when compiling the HolographicCamera.Unit project and deploying to your HoloLens 2 device.

**Comment by rdikshit** [comment]
**Question1 :**  regarding the SpectatorView.ExtrinsicsCalibration scene : On the documentation it says
Test QR Code detection for the SpectatorView.HolographicCamera app deployed in step 7.

1. Build and Deploy the SpectatorView.HolographicCamera app to your device (see step 7).
2. Open the SpectatorView.Example.Unity project.
3. Open the SpectatorView.ExtrinsicsCalibration Unity scene.

The ExtrinsicsCalibration scene is not in the Example.Unity project. Why do we need to open the SpectatorView.Example.Unity project ?

**Question 2:** Because of this error liblzma:x86-uwp failed with: BUILD_FAILED , I am not able to build src/SpectatorView.Native/SpectatorView.Native.sln 

I have been trying for days now and have raised issues on the github for vcpkg https://github.com/microsoft/vcpkg/issues/11359#

**Comment by chrisfromwork** [comment]
**Question 1:**
You can run the SpectatorView.ExtrinsicsCalibration in any project referencing the SpectatorView unity package. If you want to run calibration using your own project loaded in the editor you can. If you want to use the HolographicCamera unity project you can there as well. Feel free to do whatever you want here. There have been project refactors that may have resulted in this unclear documentation step. If you have a suggestion for how it could make more sense, feel free to provide it here.

**Question 2:**
Your issue filed against vcpkg looks like a similar issue that you filed here:
https://github.com/microsoft/vcpkg/issues/11296

Did you attempt to install both the windows 10 sdk and desktop c++ development support for visual studio?

1. Run the visual studio installer
2. Choose to modify your current install of visual studio
3. Ensure you have installed both the `Universal Windows Platform development` and `Desktop development with C++` options

**Comment by rdikshit** [comment]
Hi Chris,

I have installed both windows 10 sdk and desktop c++ development . I am still getting the same error.

Regards
Rachana Dikshit


Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by rdikshit** [comment]
Hi Chris,
I am able to build the src/SpectatorView.Native/SpectatorView.Native.sln for each of the 3 platforms successfully.Can you please confirm if the build configuration is correct as I am now getting an error when building a package for rc/HolographicCamera.Unity project  -- which references the binaries generated in Native.

![1](https://user-images.githubusercontent.com/6644233/82164373-ee9bb980-9875-11ea-8041-432e442a3aad.jpg)
![2](https://user-images.githubusercontent.com/6644233/82164374-ef345000-9875-11ea-8633-8232608e5daf.jpg)
![3](https://user-images.githubusercontent.com/6644233/82164375-ef345000-9875-11ea-8e74-f12cd12a2fe8.jpg)

I am now getting the error when creating a package for src/HolographicCamera.Unity project .
First screenshot is of the error is on unity , however as it still generated a build inspite of the error,  I continue to open the solution on VS to build 
![4](https://user-images.githubusercontent.com/6644233/82164435-391d3600-9876-11ea-9711-c61e56bc20c8.jpg)


Next screenshot  is on VS because of which I am not able to create a package for deployment.
![5](https://user-images.githubusercontent.com/6644233/82164447-4508f800-9876-11ea-900d-eede6d2ff1ad.jpg)

**Comment by rdikshit** [comment]
Hi Any updates on the above ? I am stuck at this point .
